# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: buildArtifact
  jobs:
  - job: string
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.8'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: false
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        goals: 'package -DskipTests=true'
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: 'target/fodesaf-schedulednotificacions-module-0.0.1.jar' 
        artifactName: 'fodesaf-schedulednotificacions-module-0.0.1.jar'
- stage: deployArtifact
  jobs:
  - job: string
    pool:
      vmImage: 'WNDPARALLELSLOCAL'
    steps: 
      powershell:  echo Hola Mundo
    